version: "3"

services:
  rekam-undangan-api:
    image: ghcr.io/rilgilang/rekam-undangan-api  # Use the GHCR image
    container_name: rekam-undangan-api
    hostname: rekam-undangan-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rekam-undangan-api.rule=Host(`rilgilang.duckdns.org`) && PathPrefix(`/rekam-undangan-api`)"
      - "traefik.http.routers.rekam-undangan-api.entrypoints=websecure"
      - "traefik.http.routers.rekam-undangan-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.rekam-undangan-api.loadbalancer.server.port=8081"
      - "traefik.http.middlewares.rekam-undangan-api-strip.stripprefix.prefixes=/rekam-undangan-api"
      - "traefik.http.routers.rekam-undangan-api.middlewares=rekam-undangan-api-strip"
    networks:
      - aio_default
    volumes:
      - ./.env:/opt/github.com/rilgilang/rekam-undangan-api/.env
    ports:
      - 8081:8081
    env_file:
      - .env

networks:
  aio_default:
    external: true
